LIST=LIB
EARLY_DIRS=c drvr m compat socket tar z bzip2 lzma expat cache strm jpeg png tiff login power shm_lock kalman misc ncurses2 bmetrics mmutil pps spi-master screen khronos openssl certicom_toolkits slog2 json utlfd libiconv fastmemcpy radius pci xml2 icu
LATE_DIRS=lua fontconfig mDNSResponder cares curl ipsec-tools io-pkt wmpinfo aoa fsmerkle qfim qfim-client qcrypto tss
include recurse.mk
