#!/bin/sh

#OS=aarch64-poky-linux
OS=aarch64-unknown-nto-qnx7.0.0

if [ "X$OS" != "X" ] && echo "$OS" | grep -q '`'
then
    OS=
fi

if [ "X$OS" = "X" ]
then	OS=bloat-os
    MACHINE=`uname -m | sed -e 's/ //g' | sed -e 's?/?-?g'`
    SYSTEM=`uname -s | sed -e 's/ //g' | sed -e 's?/?-?g'`
    OS="${MACHINE}-${SYSTEM}"
    if [ -f ../scripts/gnu-os ]
    then	OS=`../scripts/gnu-os | sed s/unknown-//`
    fi
    if [ -f ../../scripts/gnu-os ]
    then	OS=`../../scripts/gnu-os | sed s/unknown-//`
    fi
fi
echo $OS
